name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake (light)
        uses: Platane/snk@v3
        with:
          github_user_name: diegoarnanz-maker
          outputs: |
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate snake (dark)
        uses: Platane/snk@v3
        with:
          github_user_name: diegoarnanz-maker
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
          palette: github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
